const objects = [];
const names = [
    { firstName: "Jewel", lastName: "Gray" },
    { firstName: "Imogene", lastName: "Smith" },
    { firstName: "Barrett", lastName: "Mckenzie" },
    { firstName: "Isreal", lastName: "Boyd" },
    { firstName: "Nancy", lastName: "Arnold" },
    { firstName: "Allie", lastName: "Larson" },
    { firstName: "Lavern", lastName: "Griffin" },
    { firstName: "Monte", lastName: "Callahan" },
    { firstName: "Israel", lastName: "Mitchell" },
    { firstName: "Gene", lastName: "Vaughn" },
    { firstName: "Alan", lastName: "Holder" },
    { firstName: "Marcos", lastName: "Ryan" },
    { firstName: "June", lastName: "Mooney" },
    { firstName: "Agustin", lastName: "Pugh" },
    { firstName: "Kellie", lastName: "Burke" },
    { firstName: "Leo", lastName: "Vang" },
    { firstName: "Bernice", lastName: "Burns" },
    { firstName: "Marcus", lastName: "Osborne" },
    { firstName: "Jeffry", lastName: "Roth" },
    { firstName: "Malik", lastName: "James" },
    { firstName: "Iva", lastName: "Butler" },
    { firstName: "Hosea", lastName: "Adams" },
    { firstName: "Celina", lastName: "Lamb" },
    { firstName: "Sheri", lastName: "Vega" },
    { firstName: "Carol", lastName: "Rowland" },
    { firstName: "Mavis", lastName: "Mcneil" },
    { firstName: "Courtney", lastName: "Waters" },
    { firstName: "Ruby", lastName: "Knox" },
    { firstName: "Dewayne", lastName: "Cunningham" },
    { firstName: "Everette", lastName: "Blackwell" },
    { firstName: "Penny", lastName: "Olsen" },
    { firstName: "Tracey", lastName: "Barton" },
    { firstName: "Jose", lastName: "Carrillo" },
    { firstName: "Russell", lastName: "Mosley" },
    { firstName: "Mauricio", lastName: "Henson" },
    { firstName: "Otis", lastName: "Curtis" },
    { firstName: "Pamela", lastName: "Ramsey" },
    { firstName: "Carlo", lastName: "Moore" },
    { firstName: "Erick", lastName: "Bird" },
    { firstName: "Jeromy", lastName: "Rasmussen"},
    { firstName: "Jason", lastName: "Guerrero" },
  { firstName: "Graham", lastName: "Gates" },
  { firstName: "Tanner", lastName: "Robinson" },
  { firstName: "May", lastName: "Woodward" },
  { firstName: "Mickey", lastName: "Craig" },
  { firstName: "Shawn", lastName: "Myers" },
  { firstName: "Dan", lastName: "Becker" },
  { firstName: "Vito", lastName: "Kerr" },
  { firstName: "Humberto", lastName: "Rivers" },
  { firstName: "Major", lastName: "Mcintosh" },
  { firstName: "Anthony", lastName: "Spears" },
  { firstName: "Ivan", lastName: "Wolfe" },
  { firstName: "Glenda", lastName: "Henson" },
  { firstName: "Michelle", lastName: "Hull" },
  { firstName: "Rowena", lastName: "Holder" },
  { firstName: "Caitlin", lastName: "Stephens" },
  { firstName: "Ines", lastName: "Nolan" },
  { firstName: "Russel", lastName: "Donovan" },
  { firstName: "Christie", lastName: "Woodard" },
  { firstName: "Walter", lastName: "Pena" },
  { firstName: "Martin", lastName: "Santana" },
  { firstName: "Derrick", lastName: "Villanueva" },
  { firstName: "Mandy", lastName: "Grimes" },
  { firstName: "Carmine", lastName: "Tucker" },
  { firstName: "Samuel", lastName: "Crawford" },
  { firstName: "Michale", lastName: "Cole" },
  { firstName: "Davis", lastName: "Riley" },
  { firstName: "Horace", lastName: "Calderon" },
  { firstName: "Foster", lastName: "Guerra" },
  { firstName: "Sofia", lastName: "Mcguire" },
  { firstName: "Rafael", lastName: "Wade" },
  { firstName: "Ora", lastName: "Schmidt" },
  { firstName: "Boyd", lastName: "Calhoun" },
  { firstName: "Casandra", lastName: "Gillespie" },
  { firstName: "Dexter", lastName: "Bruce" },
  { firstName: "Mildred", lastName: "Garcia" },
  { firstName: "Guy", lastName: "Parks" },
  { firstName: "Marcel", lastName: "Matthews" },
  { firstName: "Geneva", lastName: "Kent" },
  { firstName: "Sammy", lastName: "Barry"},
  {firstName: "Laurie", lastName: "Norman"},
  {firstName: "Edwin", lastName: "Little"},
  {firstName: "Chet", lastName: "Melton"},
  {firstName: "Quinton", lastName: "Mcknight"},
  {firstName: "Kim", lastName: "Fernandez"},
  {firstName: "Amado", lastName: "Gamble"},
  {firstName: "Jasmine", lastName: "Andrews"},
  {firstName: "Cristopher", lastName: "Kaiser"},
  {firstName: "Elton", lastName: "Schaefer"},
  {firstName: "Will", lastName: "Crosby"},
  {firstName: "Tessa", lastName: "Jacobs"},
  {firstName: "Margret", lastName: "Friedman"},
  {firstName: "Linda", lastName: "Valenzuela"},
  {firstName: "Britt", lastName: "Branch"}];
  

for (let i = 0; i < names.length; i++) {
  const object = {
    firstName: names[i].firstName,
    lastName: names[i].lastName,
    email: "email" + i + "@example.com",
    image: "/anonymousPerson.jpeg",
    gpa: Math.floor(Math.random() * 5),
    campusId: Math.floor(Math.random() * 20) + 1
  };
  objects.push(object);
}