const { db, Player } = require ('./index')

const runSeed = async () => {

    const players = [
      { firstName: 'Giannis', lastName: 'Antetokounmpo', ranking: 97 },
      { firstName: 'Kevin', lastName: 'Durant', ranking: 96 },
      { firstName: 'Stephen', lastName: 'Curry', ranking: 96 },
      { firstName: 'Luka', lastName: 'Doncic', ranking: 96 },
      { firstName: 'LeBron', lastName: 'James', ranking: 96 },
      { firstName: 'Nikola', lastName: 'Jokic', ranking: 96 },
      { firstName: 'Joel', lastName: 'Embiid', ranking: 96 },
      { firstName: 'Jayson', lastName: 'Tatum', ranking: 95 },
      { firstName: 'Ja', lastName: 'Morant', ranking: 94 },
      { firstName: 'Anthony', lastName: 'Davis', ranking: 94 },
      { firstName: 'Zion', lastName: 'Williamson', ranking: 92 },
      { firstName: 'Jimmy', lastName: 'Butler', ranking: 92 },
      { firstName: 'Kawhi', lastName: 'Leonard', ranking: 91 },
      { firstName: 'Damian', lastName: 'Lillard', ranking: 91 },
      { firstName: 'Devin', lastName: 'Booker', ranking: 91 },
      { firstName: 'Shai', lastName: 'Gilgeous-Alexander', ranking: 91 },
      { firstName: 'Donovan', lastName: 'Mitchell', ranking: 90 },
      { firstName: 'Jaylen', lastName: 'Brown', ranking: 90 },
      { firstName: 'Trae', lastName: 'Young', ranking: 89 },
      { firstName: 'James', lastName: 'Harden', ranking: 89 },
      { firstName: 'Kyrie', lastName: 'Irving', ranking: 89 },
      { firstName: 'Paul', lastName: 'George', ranking: 89 },
      { firstName: 'Pascal', lastName: 'Siakam', ranking: 89 },
      { firstName: 'Tyrese', lastName: 'Haliburton', ranking: 89 },
      { firstName: 'DeMar', lastName: 'DeRozan', ranking: 88 },
      { firstName: 'Chris', lastName: 'Paul', ranking: 87 },
      { firstName: 'LaMelo', lastName: 'Ball', ranking: 87 },
      { firstName: 'Bradley', lastName: 'Beal', ranking: 87 },
      { firstName: 'Bam', lastName: 'Adebayo', ranking: 87 },
      { firstName: 'Domantas', lastName: 'Sabonis', ranking: 87 },
      { firstName: 'Kristaps', lastName: 'Porzingis', ranking: 87 },
      { firstName: 'Darius', lastName: 'Garland', ranking: 86 },
      { firstName: 'Brandon', lastName: 'Ingram', ranking: 86 },
      { firstName: 'Khris', lastName: 'Middleton', ranking: 86 },
      { firstName: 'Jaren', lastName: 'Jackson Jr', ranking: 86 },
      { firstName: 'Jrue', lastName: 'Holiday', ranking: 86 },
      { firstName: "De'Aaron", lastName: 'Fox', ranking: 86 },
      { firstName: 'Evan', lastName: 'Mobley', ranking: 85 },
      { firstName: 'Anthony', lastName: 'Edwards', ranking: 85 },
      { firstName: 'Klay', lastName: 'Thompson', ranking: 85 },
      { firstName: 'Karl-Anthony', lastName: 'Towns', ranking: 85 },
      { firstName: 'Rudy', lastName: 'Gobert', ranking: 85 },
      { firstName: 'Deandre', lastName: 'Ayton', ranking: 85 },
      { firstName: 'Jalen', lastName: 'Brunson', ranking: 85 },
      { firstName: 'Julius', lastName: 'Randle', ranking: 85 },
      { firstName: 'Lauri', lastName: 'Markkanen', ranking: 85 },
      { firstName: 'Jalen', lastName: 'Green', ranking: 84 },
      { firstName: 'Zach', lastName: 'LaVine', ranking: 84 },
      { firstName: 'Paolo', lastName: 'Banchero', ranking: 84 },
      { firstName: 'Tyrese', lastName: 'Maxey', ranking: 84 },
      { firstName: 'Tyler', lastName: 'Herro', ranking: 84 },
      { firstName: 'R.J.', lastName: 'Barrett', ranking: 84 },
      { firstName: 'C.J.', lastName: 'McCollum', ranking: 84 },
      { firstName: 'Mikal', lastName: 'Bridges', ranking: 84 },
      { firstName: 'Jarrett', lastName: 'Allen', ranking: 84 },
      { firstName: 'Andrew', lastName: 'Wiggins', ranking: 84 },
      { firstName: 'Anfernee', lastName: 'Simons', ranking: 84 },
      { firstName: 'Fred', lastName: 'VanVleet', ranking: 84 },
      { firstName: 'Christian', lastName: 'Wood', ranking: 84 },
      { firstName: 'Jerami', lastName: 'Grant', ranking: 84 },
      { firstName: 'Cade', lastName: 'Cunningham', ranking: 83 },
      { firstName: 'Scottie', lastName: 'Barnes', ranking: 83 },
      { firstName: 'Draymond', lastName: 'Green', ranking: 83 },
      { firstName: 'Jamal', lastName: 'Murray', ranking: 83 },
      { firstName: 'Jordan', lastName: 'Poole', ranking: 83 },
      { firstName: 'OG', lastName: 'Anunoby', ranking: 83 },
      { firstName: 'Desmond', lastName: 'Bane', ranking: 83 },
      { firstName: 'Franz', lastName: 'Wagner', ranking: 83 },
      { firstName: 'Robert', lastName: 'Williams III', ranking: 83 },
      { firstName: 'Miles', lastName: 'Bridges', ranking: 83 },
      { firstName: "D'Angelo", lastName: 'Russell', ranking: 83 },
      { firstName: 'Nikola', lastName: 'Vucevic', ranking: 83 },
      { firstName: 'Aaron', lastName: 'Gordon', ranking: 83 },
      { firstName: 'Keldon', lastName: 'Johnson', ranking: 83 },
      { firstName: 'Kyle', lastName: 'Kuzma', ranking: 83 },
      { firstName: 'Devin', lastName: 'Vassell', ranking: 83 },
      { firstName: 'Malcolm', lastName: 'Brogdon', ranking: 83 },
      { firstName: 'Bojan', lastName: 'Bogdanovic', ranking: 83 },
      { firstName: 'Myles', lastName: 'Turner', ranking: 83 },
      { firstName: 'Josh', lastName: 'Giddey', ranking: 82 },
      { firstName: 'Clint', lastName: 'Capela', ranking: 82 },
      { firstName: 'Tobias', lastName: 'Harris', ranking: 82 },
      { firstName: 'Jonas', lastName: 'Valaciunas', ranking: 82 },
      { firstName: 'Marcus', lastName: 'Smart', ranking: 82 },
      { firstName: 'Spencer', lastName: 'Dinwiddie', ranking: 82 },
      { firstName: 'Terry', lastName: 'Rozier III', ranking: 82 },
      { firstName: 'Brook', lastName: 'Lopez', ranking: 82 },
      { firstName: 'Jusuf', lastName: 'Nurkic', ranking: 82 },
      { firstName: 'Bobby', lastName: 'Portis', ranking: 82 },
      { firstName: 'Dejounte', lastName: 'Murray', ranking: 81 },
      { firstName: 'Mike', lastName: 'Conley', ranking: 81 },
      { firstName: 'Alperen', lastName: 'Sengun', ranking: 81 },
      { firstName: 'Mitchell', lastName: 'Robinson', ranking: 81 },
      { firstName: 'Kelly', lastName: 'Oubre Jr', ranking: 81 },
      { firstName: 'John', lastName: 'Wall', ranking: 81 },
      { firstName: 'Lonzo', lastName: 'Ball', ranking: 80 },
      { firstName: 'Michael', lastName: 'Porter Jr.', ranking: 80 },
      { firstName: 'Colin', lastName: 'Sexton', ranking: 80 },
      { firstName: 'Kyle', lastName: 'Lowry', ranking: 80 },
      { firstName: 'Bennedict', lastName: 'Mathurin', ranking: 80 }
    ];


    try { 
        await db.sync({force: true});
        await Promise.all(players.map(player => Player.create(player)));
        console.log("Seeding was successful!");
        process.kill(0);
    } catch (error) {
        console.log("There was a problem seeding the database", error);
        process.kill(0);
    }
}

runSeed();