const { db, Player } = require ('./index')

const runSeed = async () => {

    const players = [
      { firstName: 'Giannis', lastName: 'Antetokounmpo', ranking: 97, image: "/giannis.webp" },
      { firstName: 'Kevin', lastName: 'Durant', ranking: 96, image: "/durant.webp"},
      { firstName: 'Stephen', lastName: 'Curry', ranking: 96, image: "/curry.png" },
      { firstName: 'Luka', lastName: 'Doncic', ranking: 96, image: "/luka.webp" },
      { firstName: 'LeBron', lastName: 'James', ranking: 96, image: "/lebron.webp" },
      { firstName: 'Nikola', lastName: 'Jokic', ranking: 96, image: "/nikola.webp" },
      { firstName: 'Joel', lastName: 'Embiid', ranking: 96, image: "/joel.webp" },
      { firstName: 'Jayson', lastName: 'Tatum', ranking: 95, image: "/jayson.webp" },
      { firstName: 'Ja', lastName: 'Morant', ranking: 94, image: "/ja.webp" },
      { firstName: 'Anthony', lastName: 'Davis', ranking: 94, image: "/davis.png" },
      { firstName: 'Zion', lastName: 'Williamson', ranking: 92, image: "/zion.webp"  },
      { firstName: 'Jimmy', lastName: 'Butler', ranking: 92, image: "/jimmy.webp" },
      { firstName: 'Kawhi', lastName: 'Leonard', ranking: 91, image: "/kawhi.webp" },
      { firstName: 'Damian', lastName: 'Lillard', ranking: 91, image: "/damian.webp"  },
      { firstName: 'Devin', lastName: 'Booker', ranking: 91, image: "/devin.png"  },
      { firstName: 'Shai', lastName: 'Gilgeous-Alexander', ranking: 91, image: "/shai.webp"  },
      { firstName: 'Donovan', lastName: 'Mitchell', ranking: 90, image: "/donovan.webp"  },
      { firstName: 'Jaylen', lastName: 'Brown', ranking: 90, image: "/brown.webp"  },
      { firstName: 'Trae', lastName: 'Young', ranking: 89, image: "/trae.webp"  },
      { firstName: 'James', lastName: 'Harden', ranking: 89, image: "/harden.webp"  },
      { firstName: 'Kyrie', lastName: 'Irving', ranking: 89, image: "/kyrie.webp"  },
      { firstName: 'Paul', lastName: 'George', ranking: 89, image: "/paul.webp"  },
      { firstName: 'Pascal', lastName: 'Siakam', ranking: 89, image: "/pascal.webp"  },
      { firstName: 'Tyrese', lastName: 'Haliburton', ranking: 89, image: "/tyrese.webp"  },
      { firstName: 'DeMar', lastName: 'DeRozan', ranking: 88, image: "/demar.jpeg"  },
      { firstName: 'Chris', lastName: 'Paul', ranking: 87, image: "/chris.png"  },
      { firstName: 'LaMelo', lastName: 'Ball', ranking: 87, image: "/lamelo.webp"  },
      { firstName: 'Bradley', lastName: 'Beal', ranking: 87, image: "/beal.png"  },
      { firstName: 'Bam', lastName: 'Adebayo', ranking: 87, image: "/bam.webp"  },
      { firstName: 'Domantas', lastName: 'Sabonis', ranking: 87, image: "/domantas.webp"  },
      { firstName: 'Kristaps', lastName: 'Porzingis', ranking: 87, image: "/porzingis.webp"  },
      { firstName: 'Darius', lastName: 'Garland', ranking: 86, image: "/darius.png"  },
      { firstName: 'Brandon', lastName: 'Ingram', ranking: 86, image: "/ingram.webp"  },
      { firstName: 'Khris', lastName: 'Middleton', ranking: 86, image: "/middleton.webp"  },
      { firstName: 'Jaren', lastName: 'Jackson Jr', ranking: 86, image: "/jackson.webp"  },
      { firstName: 'Jrue', lastName: 'Holiday', ranking: 86, image: "/jrue.webp"  },
      { firstName: "De'Aaron", lastName: 'Fox', ranking: 86, image: "/fox.png"  },
      { firstName: 'Evan', lastName: 'Mobley', ranking: 85, image: "/mobley.webp"  },
      { firstName: 'Anthony', lastName: 'Edwards', ranking: 85, image: "/edwards.webp"  },
      { firstName: 'Klay', lastName: 'Thompson', ranking: 85, image: "/klay.webp"  },
      { firstName: 'Karl-Anthony', lastName: 'Towns', ranking: 85, image: "/towns.webp"  },
      { firstName: 'Rudy', lastName: 'Gobert', ranking: 85, image: "/rudy.webp"  },
      { firstName: 'Deandre', lastName: 'Ayton', ranking: 85, image: "/ayton.webp"  },
      { firstName: 'Jalen', lastName: 'Brunson', ranking: 85, image: "/brunson.webp"  },
      { firstName: 'Julius', lastName: 'Randle', ranking: 85, image: "/randle.webp"  },
      { firstName: 'Lauri', lastName: 'Markkanen', ranking: 85, image: "/lauri.webp"  },
      { firstName: 'Jalen', lastName: 'Green', ranking: 84, image: "/green.webp"  },
      { firstName: 'Zach', lastName: 'LaVine', ranking: 84, image: "/lavine.webp"  },
      { firstName: 'Paolo', lastName: 'Banchero', ranking: 84, image: "/paolo.png"  },
      { firstName: 'Tyrese', lastName: 'Maxey', ranking: 84, image: "/maxey.webp"  },
      { firstName: 'Tyler', lastName: 'Herro', ranking: 84, image: "/herro.png"  },
      { firstName: 'R.J.', lastName: 'Barrett', ranking: 84, image: "/barrett.webp"  },
      { firstName: 'C.J.', lastName: 'McCollum', ranking: 84, image: "/cj.webp"  },
      { firstName: 'Mikal', lastName: 'Bridges', ranking: 84, image: "/mikal.png"  },
      { firstName: 'Jarrett', lastName: 'Allen', ranking: 84, image: "/allen.png"  },
      { firstName: 'Andrew', lastName: 'Wiggins', ranking: 84, image: "/wiggins.webp"  },
      { firstName: 'Anfernee', lastName: 'Simons', ranking: 84, image: "/simons.webp"  },
      { firstName: 'Fred', lastName: 'VanVleet', ranking: 84, image: "/fred.png"  },
      { firstName: 'Christian', lastName: 'Wood', ranking: 84, image: "/wood.webp"  },
      { firstName: 'Jerami', lastName: 'Grant', ranking: 84, image: "/grant.png"  },
      { firstName: 'Cade', lastName: 'Cunningham', ranking: 83, image: "/cade.png"  },
      { firstName: 'Scottie', lastName: 'Barnes', ranking: 83, image: "/scottie.png"  },
      { firstName: 'Draymond', lastName: 'Green', ranking: 83, image: "/draymond.webp"  },
      { firstName: 'Jamal', lastName: 'Murray', ranking: 83, image: "/jamal.webp"  },
      { firstName: 'Jordan', lastName: 'Poole', ranking: 83, image: "/poole.webp"  },
      { firstName: 'OG', lastName: 'Anunoby', ranking: 83, image: "/og.webp"  },
      { firstName: 'Desmond', lastName: 'Bane', ranking: 83, image: "/desmond.jpeg"  },
      { firstName: 'Franz', lastName: 'Wagner', ranking: 83 , image: "/franz.webp" },
      { firstName: 'Robert', lastName: 'Williams III', ranking: 83, image: "/robert.png"  },
      { firstName: 'Miles', lastName: 'Bridges', ranking: 83, image: "/miles.webp"  },
      { firstName: "D'Angelo", lastName: 'Russell', ranking: 83, image: "/russell.png"  },
      { firstName: 'Nikola', lastName: 'Vucevic', ranking: 83, image: "/vucevic.webp"  },
      { firstName: 'Aaron', lastName: 'Gordon', ranking: 83, image: "/gordon.png"  },
      { firstName: 'Keldon', lastName: 'Johnson', ranking: 83, image: "/keldon.webp"  },
      { firstName: 'Kyle', lastName: 'Kuzma', ranking: 83 },
      { firstName: 'Devin', lastName: 'Vassell', ranking: 83 },
      { firstName: 'Malcolm', lastName: 'Brogdon', ranking: 83 },
      { firstName: 'Bojan', lastName: 'Bogdanovic', ranking: 83 },
      { firstName: 'Myles', lastName: 'Turner', ranking: 83 },
      { firstName: 'Josh', lastName: 'Giddey', ranking: 82 },
      { firstName: 'Clint', lastName: 'Capela', ranking: 82 },
      { firstName: 'Tobias', lastName: 'Harris', ranking: 82 },
      { firstName: 'Jonas', lastName: 'Valaciunas', ranking: 82 },
      { firstName: 'Marcus', lastName: 'Smart', ranking: 82 },
      { firstName: 'Spencer', lastName: 'Dinwiddie', ranking: 82 },
      { firstName: 'Terry', lastName: 'Rozier III', ranking: 82 },
      { firstName: 'Brook', lastName: 'Lopez', ranking: 82 },
      { firstName: 'Jusuf', lastName: 'Nurkic', ranking: 82 },
      { firstName: 'Bobby', lastName: 'Portis', ranking: 82 },
      { firstName: 'Dejounte', lastName: 'Murray', ranking: 81 },
      { firstName: 'Mike', lastName: 'Conley', ranking: 81 },
      { firstName: 'Alperen', lastName: 'Sengun', ranking: 81 },
      { firstName: 'Mitchell', lastName: 'Robinson', ranking: 81 },
      { firstName: 'Kelly', lastName: 'Oubre Jr', ranking: 81 },
      { firstName: 'John', lastName: 'Wall', ranking: 81 },
      { firstName: 'Lonzo', lastName: 'Ball', ranking: 80 },
      { firstName: 'Michael', lastName: 'Porter Jr.', ranking: 80 },
      { firstName: 'Colin', lastName: 'Sexton', ranking: 80 },
      { firstName: 'Kyle', lastName: 'Lowry', ranking: 80 },
      { firstName: 'Bennedict', lastName: 'Mathurin', ranking: 80 }
    ];

    try { 
        await db.sync({force: true});
        await Promise.all(players.map(player => Player.create(player)));
        console.log("Seeding was successful!");
        process.kill(0);
    } catch (error) {
        console.log("There was a problem seeding the database", error);
        process.kill(0);
    }
}

runSeed();