let players = [{first: "Giannis", last: "Antetokounmpo", ranking: 97},
{first: "Kevin", last: "Durant", ranking: 96},
{first: "Stephen", last: "Curry", ranking: 96},
{first: "Luka", last: "Doncic", ranking: 96},
{first: "LeBron", last: "James", ranking: 96},
{first: "Nikola", last: "Jokic", ranking: 96},
{first: "Joel", last: "Embiid", ranking: 96},
{first: "Jayson", last: "Tatum", ranking: 95},
{first: "Ja", last: "Morant", ranking: 94},
{first: "Anthony", last: "Davis", ranking: 94},
{first: "Zion", last: "Williamson", ranking: 92},
{first: "Jimmy", last: "Butler", ranking: 92},
{first: "Kawhi", last: "Leonard", ranking: 91},
{first: "Damian", last: "Lillard", ranking: 91},
{first: "Devin", last: "Booker", ranking: 91},
{first: "Shai", last: "Gilgeous-Alexander", ranking: 91},
{first: "Donovan", last: "Mitchell", ranking: 90},
{first: "Jaylen", last: "Brown", ranking: 90},
{first: "Trae", last: "Young", ranking: 89},
{first: "James", last: "Harden", ranking: 89},
{first: "Kyrie", last: "Irving", ranking: 89},
{first: "Paul", last: "George", ranking: 89},
{first: "Pascal", last: "Siakam", ranking: 89},
{first: "Tyrese", last: "Haliburton", ranking: 89},
{first: "DeMar", last: "DeRozan", ranking: 88},
{first: "Chris", last: "Paul", ranking: 87},
{first: "LaMelo", last: "Ball", ranking: 87},
{first: "Bradley", last: "Beal", ranking: 87},
{first: "Bam", last: "Adebayo", ranking: 87},
{first: "Domantas", last: "Sabonis", ranking: 87},
{first: "Kristaps", last: "Porzingis", ranking: 87},
{first: "Darius", last: "Garland", ranking: 86},
{first: "Brandon", last: "Ingram", ranking: 86},
{first: "Khris", last: "Middleton", ranking: 86},
{first: "Jaren", last: "Jackson Jr", ranking: 86},
{first: "Jrue", last: "Holiday", ranking: 86},
{first: "De'Aaron", last: "Fox", ranking: 86},
{first: "Evan", last: "Mobley", ranking: 85},
{first: "Anthony", last: "Edwards", ranking: 85},
{first: "Klay", last: "Thompson", ranking: 85},
{first: "Karl-Anthony", last: "Towns", ranking: 85},
{first: "Rudy", last: "Gobert", ranking: 85},
{first: "Deandre", last: "Ayton", ranking: 85},
{first: "Jalen", last: "Brunson", ranking: 85},
{first: "Julius", last: "Randle", ranking: 85},
{first: "Lauri", last: "Markkanen", ranking: 85},
{first: "Jalen", last: "Green", ranking: 84},
{first: "Zach", last: "LaVine", ranking: 84},
{first: "Paolo", last: "Banchero", ranking: 84},
{first: "Tyrese", last: "Maxey", ranking: 84},
{first: "Tyler", last: "Herro", ranking: 84},
{first: "R.J.", last: "Barrett", ranking: 84},
{first: "C.J.", last: "McCollum", ranking: 84},
{first: "Mikal", last: "Bridges", ranking: 84},
{first: "Jarrett", last: "Allen", ranking: 84},
{first: "Andrew", last: "Wiggins", ranking: 84},
{first: "Anfernee", last: "Simons", ranking: 84},
{first: "Fred", last: "VanVleet", ranking: 84},
{first: "Christian", last: "Wood", ranking: 84},
{first: "Jerami", last: "Grant", ranking: 84},
{first: "Cade", last: "Cunningham", ranking: 83},
{first: "Scottie", last: "Barnes", ranking: 83},
{first: "Draymond", last: "Green", ranking: 83},
{first: "Jamal", last: "Murray", ranking: 83},
{first: "Jordan", last: "Poole", ranking: 83},
{first: "OG", last: "Anunoby", ranking: 83},
{first: "Desmond", last: "Bane", ranking: 83},
{first: "Franz", last: "Wagner", ranking: 83},
{first: "Robert", last: "Williams III", ranking: 83},
{first: "Miles", last: "Bridges", ranking: 83},
{first: "D'Angelo", last: "Russell", ranking: 83},
{first: "Nikola", last: "Vucevic", ranking: 83},
{first: "Aaron", last: "Gordon", ranking: 83},
{first: "Keldon", last: "Johnson", ranking: 83},
{first: "Kyle", last: "Kuzma", ranking: 83},
{first: "Devin", last: "Vassell", ranking: 83},
{first: "Malcolm", last: "Brogdon", ranking: 83},
{first: "Bojan", last: "Bogdanovic", ranking: 83},
{first: "Myles", last: "Turner", ranking: 83},
{first: "Josh", last: "Giddey", ranking: 82},
{first: "Clint", last: "Capela", ranking: 82},
{first: "Tobias", last: "Harris", ranking: 82},
{first: "Jonas", last: "Valaciunas", ranking: 82},
{first: "Marcus", last: "Smart", ranking: 82},
{first: "Spencer", last: "Dinwiddie", ranking: 82},
{first: "Terry", last: "Rozier III", ranking: 82},
{first: "Brook", last: "Lopez", ranking: 82},
{first: "Jusuf", last: "Nurkic", ranking: 82},
{first: "Bobby", last: "Portis", ranking: 82},
{first: "Dejounte", last: "Murray", ranking: 81},
{first: "Mike", last: "Conley", ranking: 81},
{first: "Alperen", last: "Sengun", ranking: 81},
{first: "Mitchell", last: "Robinson", ranking: 81},
{first: "Kelly", last: "Oubre Jr", ranking: 81},
{first: "John", last: "Wall", ranking: 81},
{first: "Lonzo", last: "Ball", ranking: 80},
{first: "Michael", last: "Porter Jr.", ranking: 80},
{first: "Colin", last: "Sexton", ranking: 80},
{first: "Kyle", last: "Lowry", ranking: 80},
{first: "Bennedict", last: "Mathurin", ranking: 80}
]

let playersArray = []
for (let i=0; i<players.length;i++) {
    const obj  = {
        firstName: players[i].first,
        lastName: players[i].last,
        ranking: players[i].ranking
    }
    playersArray.push(obj)
}

console.log(playersArray)